### ISSUE TITLE
Floor plan elements in Home Assistant

### ISSUE THREAD

**Issue by goatchurchprime** [Nitwel/Immersive-Home#168]
As part of storing the design and layout of the Immersive Home geometry back into Home Assistant (so that it can be shared with a second headset, and backed up), you should generate Floor Plan pages for each room, as described like this.
 https://community.home-assistant.io/t/yet-another-sh3d-floor-plan-plugin/684148

They're overdoing the graphics in these examples.  Basically you get a single background SVG or image for each room, and then the elements are laid out by percentage values like in a css definition:

```yaml
- type: state-icon
    entity: light.bathroom
    title: null
    tap_action:
      action: toggle
    style:
      top: 44.76%
      left: 25.65%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
```

So even if you don't use the headset again you've got your elements in a more spatial UI in the screen app, and the work isn't wasted.  It's an excellent way to get an external view of what ImmersiveHome has stored into the database.
